-- COM2058 Ogrenme: Mini COMPANY semasi (sinav mantigi, kucuk veri)
-- Calistir: mysql -u root -p < 00_company_mini_schema.sql

DROP DATABASE IF EXISTS company_ogrenme;
CREATE DATABASE company_ogrenme CHARACTER SET utf8mb4;
USE company_ogrenme;

CREATE TABLE DEPARTMENT (
  Dnumber   INT PRIMARY KEY,
  Dname     VARCHAR(30) NOT NULL UNIQUE,
  Mgr_ssn   CHAR(9),
  Mgr_start_date DATE
);

CREATE TABLE EMPLOYEE (
  Ssn       CHAR(9) PRIMARY KEY,
  Fname     VARCHAR(15) NOT NULL,
  Lname     VARCHAR(15) NOT NULL,
  Salary    DECIMAL(10,2) CHECK (Salary > 0),
  Dno       INT,
  Super_ssn CHAR(9),
  FOREIGN KEY (Dno) REFERENCES DEPARTMENT(Dnumber)
    ON DELETE SET DEFAULT
    ON UPDATE CASCADE,
  FOREIGN KEY (Super_ssn) REFERENCES EMPLOYEE(Ssn)
    ON DELETE SET NULL
);

ALTER TABLE DEPARTMENT
  ADD FOREIGN KEY (Mgr_ssn) REFERENCES EMPLOYEE(Ssn)
    ON DELETE SET NULL;

CREATE TABLE PROJECT (
  Pnumber   INT PRIMARY KEY,
  Pname     VARCHAR(30) NOT NULL,
  Plocation VARCHAR(15),
  Dnum      INT NOT NULL DEFAULT 1,
  FOREIGN KEY (Dnum) REFERENCES DEPARTMENT(Dnumber)
    ON DELETE SET DEFAULT
    ON UPDATE CASCADE
);

CREATE TABLE WORKS_ON (
  Essn   CHAR(9) NOT NULL,
  Pno    INT NOT NULL,
  Hours  DECIMAL(4,1) CHECK (Hours > 0 AND Hours <= 168),
  PRIMARY KEY (Essn, Pno),
  FOREIGN KEY (Essn) REFERENCES EMPLOYEE(Ssn)
    ON DELETE CASCADE,
  FOREIGN KEY (Pno) REFERENCES PROJECT(Pnumber)
    ON DELETE SET DEFAULT
    ON UPDATE CASCADE
);

CREATE TABLE DEPT_LOCATIONS (
  Dnumber   INT NOT NULL,
  Dlocation VARCHAR(15) NOT NULL,
  PRIMARY KEY (Dnumber, Dlocation),
  FOREIGN KEY (Dnumber) REFERENCES DEPARTMENT(Dnumber)
    ON DELETE CASCADE
);

-- Ornek veri
INSERT INTO DEPARTMENT VALUES (1, 'Headquarters', NULL, '1981-06-19');
INSERT INTO DEPARTMENT VALUES (5, 'Research', NULL, '1988-05-22');

INSERT INTO EMPLOYEE VALUES
  ('123456789', 'John', 'Smith', 30000, 5, NULL),
  ('333445555', 'Joy', 'English', 28000, 5, '123456789'),
  ('999887777', 'Alicia', 'Zelaya', 25000, 4, NULL);

UPDATE DEPARTMENT SET Mgr_ssn = '333445555' WHERE Dnumber = 5;
UPDATE DEPARTMENT SET Mgr_ssn = '123456789' WHERE Dnumber = 1;

INSERT INTO PROJECT VALUES (1, 'ProductX', 'Bellaire', 5);
INSERT INTO PROJECT VALUES (2, 'ProductY', 'Sugarland', 5);
INSERT INTO PROJECT VALUES (3, 'ProductZ', 'Houston', 5);

INSERT INTO WORKS_ON VALUES ('123456789', 1, 32.5);
INSERT INTO WORKS_ON VALUES ('123456789', 2, 7.5);
INSERT INTO WORKS_ON VALUES ('333445555', 2, 10.0);

INSERT INTO DEPT_LOCATIONS VALUES (1, 'Houston');
INSERT INTO DEPT_LOCATIONS VALUES (5, 'Bellaire');
INSERT INTO DEPT_LOCATIONS VALUES (5, 'Sugarland');

SELECT 'company_ogrenme hazir' AS durum;
