-- LAB6 - CUSTOMER / PART / ORDERS
-- Kaynak: ../LAB_eski/LAB6/SOLUTION.txt

CREATE DATABASE IF NOT EXISTS LAB6;
USE LAB6;

CREATE TABLE CUSTOMER (
  NAME CHAR(50) PRIMARY KEY,
  ADDRESS CHAR(50),
  STATE CHAR(10),
  ZIP INT,
  PHONE CHAR(50),
  REMARKS CHAR(10)
);

CREATE TABLE PART (
  PARTNUM INT PRIMARY KEY,
  DESCRIPTION CHAR(50),
  PRICE DOUBLE
);

CREATE TABLE ORDERS (
  ORDEREDON DATE,
  NAME CHAR(50),
  PARTNUM INT,
  QUANTITY INT,
  REMARKS CHAR(20),
  PRIMARY KEY (ORDEREDON, NAME, PARTNUM)
);

ALTER TABLE ORDERS ADD FOREIGN KEY (PARTNUM) REFERENCES PART(PARTNUM);
ALTER TABLE ORDERS ADD FOREIGN KEY (NAME) REFERENCES CUSTOMER(NAME);

-- Ornek veri ve sorgular SOLUTION.txt ile ayni:

-- 1) Toplam siparis tutari
SELECT SUM(O.QUANTITY * P.PRICE) AS total_revenue
FROM ORDERS O, PART P
WHERE O.PARTNUM = P.PARTNUM;

-- 2) Musteri bazinda toplam adet
SELECT C.NAME, SUM(O.QUANTITY) AS total_qty
FROM CUSTOMER C, ORDERS O
WHERE O.NAME = C.NAME
GROUP BY C.NAME;

-- 3) Parca bazinda toplam adet
SELECT P.DESCRIPTION, SUM(O.QUANTITY) AS total_qty
FROM PART P, ORDERS O
WHERE P.PARTNUM = O.PARTNUM
GROUP BY P.DESCRIPTION;

-- 4) Mountain bike toplam gelir
SELECT SUM(O.QUANTITY * P.PRICE) AS bike_revenue
FROM ORDERS O, PART P
WHERE O.PARTNUM = P.PARTNUM AND P.DESCRIPTION = 'MOUNTAIN BIKE';

-- 5) Uc tablo join - musteri siparis detayi
SELECT C.NAME, C.ADDRESS, O.QUANTITY * P.PRICE AS line_total, P.DESCRIPTION
FROM CUSTOMER C
JOIN ORDERS O ON C.NAME = O.NAME
JOIN PART P ON O.PARTNUM = P.PARTNUM;

-- 6) Belirli siparis satiri
SELECT O.ORDEREDON, O.NAME, O.PARTNUM, O.QUANTITY
FROM ORDERS O
WHERE O.PARTNUM = 10 AND O.QUANTITY = 1 AND O.NAME = 'TRUE WHEEL';
